spring.datasource.url=postgresql://neondb_owner:npg_U9B0zCXewdHE@ep-autumn-band-ad1icwrb-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.jpa.hibernate.ddl-auto=update

#Log out sql queries or comment these lines out with a hashtag
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
